# Generated by Django 5.0.2 on 2024-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_aliment', models.CharField(max_length=50)),
                ('sanatate', models.IntegerField()),
                ('kcal', models.IntegerField()),
                ('proteine', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fats', models.IntegerField()),
            ],
        ),
    ]
