# Generated by Django 5.0.2 on 2024-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_test', models.CharField(max_length=20)),
            ],
        ),
    ]
