# Generated by Django 5.0.2 on 2024-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokup', '0003_myuser_delete_aliment_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('kcal', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('carbs', models.IntegerField()),
            ],
        ),
    ]
